# Copyright (c) Spectro Cloud
# SPDX-License-Identifier: MPL-2.0

branches: [main]
repositoryUrl: https://github.com/spectrocloud/hello-universe-api
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - - "@semantic-release/exec"
    - analyzeCommitsCmd: echo 'NEW_VERSION=false' > VERSION.env
      verifyReleaseCmd: |-
        echo 'export VERSION=${nextRelease.version}
        NEW_VERSION=true' > VERSION.env
  - - "@semantic-release/github"
    - assets:
        - "*.zip"
